### ISSUE TITLE
FEATURE Request: Update Conversation via text input and chatbox

### ISSUE THREAD

**Issue by Meistro77** [cameronking4/VapiBlocks#1]
FEATURE Request: Update Conversation via text input and chatbox

**Comment by Meistro77** [comment]
basically im thinking it could be a block.

**Comment by cameronking4** [comment]
Like a combined chat bot and voice?

**Comment by cameronking4** [comment]
Or even simpler could be a free form textbox that u can add prompt at any time in conversation?

**Comment by Meistro77** [comment]
exactly i have another idea you might like. How can we connect?

**Comment by cameronking4** [comment]
Maybe i start a slack or discord for Vapiblocks. 
In meantime hmu on [Twitter ](https://x.com/cameronyking4 )or [Linkedin](https://www.linkedin.com/in/cameronyking/)
